### ISSUE TITLE
Some issues and questions

### ISSUE THREAD

**Issue by yfdyh000** [Infocatcher/Link_Properties_Plus#24]
I see some issues and questions duing localization testing.
I can't reproduce some features:
contextOnSelection
linkPropsPlus.copy*
linkPropsPlus.opts.downloadDialog

showInAppMenu is not working properly in Fx28.0, I see it is placed on DevTools menu instead of the App menu.

**Comment by Infocatcher** [comment]
> contextOnSelection

This is for not clickable links, like here: https://github.com/piroor/textlink/blob/master/tests/fixtures/testcase.txt

> linkPropsPlus.copy*

<img src="https://addons.cdn.mozilla.net/user-media/previews/full/168/168180.png?modified=1447115284" alt="Context menu for rows">

> linkPropsPlus.opts.downloadDialog

Second options group:
<img src="https://addons.cdn.mozilla.net/user-media/previews/full/168/168172.png?modified=1447115284" alt="Options - General">

> showInAppMenu is not working properly in Fx28.0, I see it is placed on DevTools menu instead of the App menu.

Yes... but inside App menu.
May be it's better to change description to "Show item in App menu – Web Developer".

**Comment by yfdyh000** [comment]
Thanks you.

> Second options group:

**Comment by Infocatcher** [comment]
> I don't know how to understand the "Opening file dialog", where is it?

Will be opened for any downloadable link:
<img src="https://addons.cdn.mozilla.net/user-media/previews/full/168/168170.png?modified=1447115284" alt="Download dialog">
E.g. for this one: https://github.com/Infocatcher/Link_Properties_Plus/archive/master.zip

**Comment by yfdyh000** [comment]
Thank you, got it. My thoughts strayed to Open File (Ctrl+O) and confused. "Opening file from Web" may be more clearer.
